# Generated by Django 5.2.4 on 2025-07-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometria',
            fields=[
                ('id_geometria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('geojson', models.JSONField(help_text='Geometría almacenada en formato GeoJSON')),
                ('monitoreo_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometrias', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'Geometría',
                'verbose_name_plural': 'Geometrías',
                'ordering': ['-creado_en'],
            },
        ),
    ]
